In [1]:
print("Hello")

Hello


In [1]:
import numpy as np
zeros=np.zeros((3,4))
print(f"Zeros matrix:- {zeros}")
ones=np.ones((3,4))
print(f"Ones:- {ones}")
full=np.full((3,4),5)
print(f"Full:- {full}")
print(full*zeros)
random=np.random.random((3,4))
print(random)
sequence=np.arange(0,11,3)
print(sequence)

Zeros matrix:- [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:- [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full:- [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.53786256 0.57486379 0.62576753 0.48762743]
 [0.77396288 0.83577224 0.02784236 0.26525168]
 [0.93782335 0.89003927 0.88111219 0.86085247]]
[0 3 6 9]


### Vector Tensor and Matrix

In [6]:
import numpy as np
vector=np.array([3,5,7])
print(f"Vector:- {vector}")

matrix=np.array([[3,5,6],
                [6,3,6]])
print(f"Matrix:- {matrix}")

tensor=np.array([[[3,4],[5,6]],
                [[6,7],[7,3]]])
print(f"Tensor:- {tensor}")

Vector:- [3 5 7]
Matrix:- [[3 5 6]
 [6 3 6]]
Tensor:- [[[3 4]
  [5 6]]

 [[6 7]
  [7 3]]]


## Array properties


In [7]:
arr=np.array([[3,4],
                [5,7]])
print("Shape: ",arr.shape)
print("Dimensions: ",arr.ndim)
print("DType: ",arr.dtype)
print("Size: ",arr.size)


Shape:  (2, 2)
Dimensions:  2
DType:  int64
Size:  4


## Array Reshaping


In [16]:
arr=np.array([[3,4,5],
                [4,7,2]])
print("reshaped: ",arr.reshape(3,2))
print("Array: ",arr)
print("Flattened array: ",arr.flatten()) #changes main array
print("Array: ",arr.ravel())#return view instead of copy
#Transpose
arr=np.array([[3,4,5],
                [4,7,2]])
print("Transpose: ",arr.T)

reshaped:  [[3 4]
 [5 4]
 [7 2]]
Array:  [[3 4 5]
 [4 7 2]]
Flattened array:  [3 4 5 4 7 2]
Array:  [3 4 5 4 7 2]
Transpose:  [[3 4]
 [4 7]
 [5 2]]
