### Advance Operations with Buisiness Examples


In [2]:
import numpy as np

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani      
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites      
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub       
    [4, 180000, 210000, 240000, 270000],  # Burger Point     
    [5, 160000, 185000, 205000, 230000]   # Chai Point      
])
print("=======Zomato Sales Analysis=======")
print("Data Shape:-",sales_data.shape)
print("Data of First three: ",sales_data[:3])


=======Zomato Sales Analysis=======
Data Shape:- (5, 5)
Data of First three:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [4]:
## Total Sales per Year
print("Per Year Sale:-",np.sum(sales_data,axis=0))
print("Restro Sale:-",np.sum(sales_data,axis=1))

## Minimum Sales
print(np.min(sales_data[:,1:],axis=1))

##Maximum sales per Year
print(np.max(sales_data[: ,1:],axis=0))

##Average Sales per Resturant 
print(np.mean(sales_data[: ,1:],axis=1))

##Cummulative Sales
print(np.cumsum)
 

Per Year Sale:- [     15  810000  945000 1085000 1240000]
Restro Sale:- [800001 610002 990003 900004 780005]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]
<function cumsum at 0x7443e370c1a0>


In [5]:
vector1=np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])

print("Vector Addition: ",vector1+vector2)
print("Product: ",vector1*vector2)
print("Dot Product: ",np.dot(vector1,vector2))


Vector Addition:  [ 7  9 11 13 15]
Product:  [ 6 14 24 36 50]
Dot Product:  130


In [6]:
resturant_types=np.array(["Paradise Biryani","Beijing Bites","Pizza Hub","Burger Point","Chai Point"])
vectorize_Operations=np.vectorize(str.upper)
print("In Uppercase: ",vectorize_Operations(resturant_types))

In Uppercase:  ['PARADISE BIRYANI' 'BEIJING BITES' 'PIZZA HUB' 'BURGER POINT'
 'CHAI POINT']


In [7]:
##Monthly Average
monthly_avg=sales_data[: ,1:]/12
print("Monthly Average: ",monthly_avg)


Monthly Average:  [[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
