# Array Operations


In [ ]:
import numpy as np
arr=np.array([3,4,5,4,6,43,56,454,4,4,4,4])
print("Slicing:- ",arr[1:3])
print("Slicing With Steps:- ",arr[1:7:2])

In [ ]:
import numpy as np
arr_2d=np.array([[3,4,5],
                [2,5,8],
                [4,6,3]])
print("Specific Element:- ",arr_2d[2,1])
print("Entire Row:- ",arr_2d[1])
print("Entire Colume:- ",arr_2d[:,2])

In [ ]:
unshorted=np.array([3,5,3,6])
print("Shorted:-",np.sort(unshorted))

## Filter

In [2]:
arr=np.array([3,4,5,6,7,8,9,10,11,12,13,14])
even=arr[arr%2==0]
print("Even:-", even)

Even:- [ 4  6  8 10 12 14]


## Filter With Mask

In [3]:
arr=np.array([3,4,5,6,7,8,9,10,11,12,13,14])
mask= arr%2==0
print("Even:-", arr[mask])


Even:- [ 4  6  8 10 12 14]


## Fancy Indexing VS np.where()


In [4]:
arr=np.array([3,4,5,6,7,8,9,10,11,12,13,14])
indices=[2,4,7,2]
print("Element:- ",arr[indices])
where_result=np.where(arr>5) #Stores Indices
print(where_result)
print("where result:- ",arr[where_result])

Element:-  [ 5  7 10  5]
(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]),)
where result:-  [ 6  7  8  9 10 11 12 13 14]


In [5]:
arr=np.array([3,4,5,6,7,8,9,10,11,12,13,14])
where_result=np.where(arr>6,arr*10,arr*5) 
## it is like if arr>6 do arr*10 if not do arr*5
print(where_result)

[ 15  20  25  30  70  80  90 100 110 120 130 140]


## Adding and removing array


In [ ]:
arr1=[3,4,5]
arr2=[3,7,8]
combined=np.concatenate((arr1,arr2))
print(combined)

## Array Compatibality

In [6]:
a=np.array([3,5,2])
b=np.array([5,7,2])
c=np.array([2,6,8])
d=np.array([3,4,6,7])
print(f"Compatiability of a and b is {np.shape(a)==np.shape(b)}")
print(f"Compatiability of a and d is {np.shape(a)==np.shape(d)}")


Compatiability of a and b is True
Compatiability of a and d is False


In [7]:
a=np.array([[3,4],
            [7,1]])
b=np.array([5,8])
new_row=np.vstack((a,b))
print(new_row)
c=([[3],[4]])
new_column=np.hstack((a,c))
print(new_column)

[[3 4]
 [7 1]
 [5 8]]
[[3 4 3]
 [7 1 4]]


## Deletion

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,0])
after_deletion=np.delete(arr,5)
print(after_deletion)